#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"
CF_EXE=$REPO_ROOT/support/clang-format

STYLE=$(git config --get hooks.clangformat.style)
if [ -n "${STYLE}" ] ; then
  STYLEARG="-style=${STYLE}"
else
  STYLEARG=""
fi

if ! "${CF_EXE}" --version | grep 'clang-format version 14\.0' >/dev/null 2>/dev/null; then
    echo "clang-format version 14.0 is required (exactly)"
    exit 1
fi

format_file() {
  file="${1}"
  if [ -f $file ]; then
    echo "Running clang-format on ${1}"
    ${CF_EXE} -i ${STYLEARG} ${1} || exit 1
    git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp|cu|hip)$' ` ; do
      format_file "${file}"
    done
    ;;
esac
