name: ExaChem_CI

on: 
  push:
    paths-ignore:
      - docs  
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1000
    strategy:
      max-parallel: 3
      matrix:
        os: 
          - [self-hosted, rocky10]
          - [self-hosted, macos]
        backend:
          - ga
        mpi_impl:
          - mpich
        cxx:
          - g++
        cc:
          - gcc
        fc:
          - gfortran
        use_cuda:
          - no-cuda          
        use_scalapack:
          - no-scalapack         
        use_elpa:
          - no-elpa
        include:
          - os: [self-hosted, rocky10]
            mpi_impl: mpich
            cxx: clang++
            cc: clang
            fc: gfortran
            backend: ga
            use_cuda: no-cuda
            use_scalapack: no-scalapack
            use_elpa: no-elpa
          - os: [self-hosted, rocky10]
            mpi_impl: mpich
            cxx: g++
            cc: gcc
            fc: gfortran
            backend: ga
            use_cuda: cuda
            use_scalapack: no-scalapack
            use_elpa: no-elpa
          - os: [self-hosted, rocky10]
            mpi_impl: mpich
            cxx: g++
            cc: gcc
            fc: gfortran
            backend: ga
            use_cuda: cuda
            use_scalapack: scalapack
            use_elpa: elpa
          - os: [self-hosted, rocky10]
            mpi_impl: mpich
            cxx: g++
            cc: gcc
            fc: gfortran
            backend: ga
            use_cuda: no-cuda
            use_scalapack: scalapack
            use_elpa: no-elpa
          - os: [self-hosted, macos]
            mpi_impl: mpich
            cxx: g++
            cc: gcc
            fc: gfortran
            backend: ga
            use_cuda: no-cuda
            use_scalapack: no-scalapack
            use_elpa: no-elpa
      fail-fast: true

    env:
      MPI_IMPL: ${{ matrix.mpi_impl }}
      CXX: ${{ matrix.cxx }}
      CC: ${{ matrix.cc }}
      FC: ${{ matrix.fc }}

    steps:
    - uses: actions/checkout@v4
    - name: Check SIMD
      id: get-simd
      run: |
        chmod +x ${GITHUB_WORKSPACE}/.github/workflows/scripts/check_simd.sh
        echo "simd=$(${GITHUB_WORKSPACE}/.github/workflows/scripts/check_simd.sh)" >> $GITHUB_ENV
      shell: bash

    - name: Set build option defaults
      id: set-build-option-defaults
      run: |
        echo "INSTALL_PATH=$GITHUB_WORKSPACE/install" >> $GITHUB_ENV
        echo "USE_CUDA=OFF" >> $GITHUB_ENV
        echo "USE_SCALAPACK=OFF" >> $GITHUB_ENV
        echo "USE_ELPA=OFF" >> $GITHUB_ENV
        echo "EC_NPROC=8" >> $GITHUB_ENV
        echo "LA_VENDOR=OpenBLAS" >> $GITHUB_ENV
      shell: bash

    - name: Set cuda build options
      if: ${{ matrix.use_cuda == 'cuda' }}
      shell: bash
      run: |
        echo "USE_CUDA=ON" >> $GITHUB_ENV

    - name: Set scalapack build options
      if: ${{ matrix.use_scalapack == 'scalapack' }}
      shell: bash
      run: |
        echo "USE_SCALAPACK=ON" >> $GITHUB_ENV

    - name: Set elpa build options
      if: ${{ matrix.use_elpa == 'elpa' }}
      shell: bash
      run: |
        echo "USE_ELPA=ON" >> $GITHUB_ENV

    - name: load llvm
      if: ${{ matrix.cc == 'clang' && matrix.cxx == 'clang++' && matrix.fc == 'gfortran' && matrix.os[1] == 'rocky10' }}
      shell: bash
      run: |
        module load llvm/20.1.8
        echo "CC=$(which clang)" >> $GITHUB_ENV
        echo "CXX=$(which clang++)" >> $GITHUB_ENV
        echo "FC=$(which gfortran)" >> $GITHUB_ENV
        echo "LA_VENDOR=IntelMKL" >> $GITHUB_ENV
        echo "MKLROOT=$MKLROOT" >> $GITHUB_ENV

    - name: macos env
      if: ${{ matrix.os[1] == 'macos' }}
      shell: bash
      run: |
        echo "LA_VENDOR=OpenBLAS" >> $GITHUB_ENV

    - name: Cache install steps (backend = ga)
      if: ${{ matrix.backend == 'ga' }}
      id: exachem-cache-install
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/install
        key: ${{ runner.os }}-${{ matrix.mpi_impl }}-${{ matrix.cc }}-${{ matrix.cxx }}-simd${{ env.simd }}-exachem-ga-${{ matrix.use_cuda }}-${{ matrix.use_scalapack }}-${{ matrix.use_elpa }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.mpi_impl }}-${{ matrix.cc }}-${{ matrix.cxx }}-simd${{ env.simd }}-exachem-ga-${{ matrix.use_cuda }}-${{ matrix.use_scalapack }}-${{ matrix.use_elpa }}-

    - name: show-mpi
      run: |
        mpicc   -show
        mpifort -show
        mpicxx  -show
        mpiexec --version

    - name: show-compilers
      run: |
        $CC     --version
        $CXX    --version
        $FC     --version
        python3 --version
      shell: bash

    - name: build exachem (backend = ga)
      if: ${{ matrix.backend == 'ga' }}
      id: build_exachem
      run: |
        echo "CI_NRANKS=3" >> $GITHUB_ENV

        # TAMM build
        git clone https://github.com/NWChemEx/TAMM $GITHUB_WORKSPACE/TAMM
        cd $GITHUB_WORKSPACE/TAMM
        LINALG_PREFIX_FLAG=""
        if [[ "${{ env.LA_VENDOR }}" == "IntelMKL" ]]; then
          LINALG_PREFIX_FLAG="-DLINALG_PREFIX=$MKLROOT"
        fi
        cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PATH }} -DLINALG_VENDOR=${{ env.LA_VENDOR }} $LINALG_PREFIX_FLAG -DGPU_ARCH=70 -DMODULES="CC" -DTAMM_ENABLE_CUDA=${{ env.USE_CUDA }} -DUSE_SCALAPACK=${{ env.USE_SCALAPACK }} -DTAMM_ENABLE_ELPA=${{ env.USE_ELPA }}
        cd build
        make -j${{ env.EC_NPROC }}
        make install

        # ExaChem build
        cd $GITHUB_WORKSPACE
        cmake -H. -Bbuild -DGPU_ARCH=70 -DMODULES="CC" -DTAMM_ENABLE_CUDA=${{ env.USE_CUDA }} -DTAMM_ENABLE_ELPA=${{ env.USE_ELPA }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_PATH }}
        cd build
        make -j${{ env.EC_NPROC }}
        make install

    - name: ctest
      run: |
        cd $GITHUB_WORKSPACE/build
        export PATH=$PATH:$GITHUB_WORKSPACE/install/bin
        echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
        # ctest -VV
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_HOME/lib64 || true
        $GITHUB_WORKSPACE/ci/scripts/run_ci $GITHUB_WORKSPACE $GITHUB_WORKSPACE/build/methods_stage/${{ env.INSTALL_PATH }}/methods/ExaChem ${{ env.CI_NRANKS }} ${{ env.CI_MPIEXEC }}

    # - name: gcovr
    #   run: |
    #     cd $GITHUB_WORKSPACE
    #     gcovr --root . --exclude build --exclude tests --xml ./coverage.xml
    #     ls -al .
    # - uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./coverage.xml
